1.3.1 Задание

In [7]:
import numpy as np

x = np.zeros((8, 8))

for i in range(1, 65, 2):
    x[i // 8, i % 8] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


1.3.2 Задание

In [13]:
import numpy as np
x = np.arange(5) 
x = np.block([x,x,x,x, x]).reshape(5,5)
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3 Задание

In [16]:
from numpy.random import default_rng

default_rng(1).random((3,3,3))

array([[[0.51182162, 0.9504637 , 0.14415961],
        [0.94864945, 0.31183145, 0.42332645],
        [0.82770259, 0.40919914, 0.54959369]],

       [[0.02755911, 0.75351311, 0.53814331],
        [0.32973172, 0.7884287 , 0.30319483],
        [0.45349789, 0.1340417 , 0.40311299]],

       [[0.20345524, 0.26231334, 0.75036467],
        [0.28040876, 0.48519097, 0.9807372 ],
        [0.96165719, 0.72478994, 0.54122686]]])

1.3.4 Задание

In [36]:
size = 7
b = [i for i in range(size)] 
b = b[1:len(b)-1]

a = np.ones((size,size))
for i in range(size):
    for j in range(size):
        if (i in b) and (j in b):
            a[i][j] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


1.3.5 Задание

In [40]:
import numpy as np
a = np.array([1,5,3,2,8,9,10])
a = np.sort(a)[::-1]
print(a)


[10  9  8  5  3  2  1]


1.3.6 Задание

In [46]:
from numpy.random import default_rng

matrix = default_rng(1).random((5,5))
print("Форма матрицы:", matrix.shape)
print("Размер матрицы:", matrix.size)
print("Размерность матрицы: ", matrix.ndim)
# print(matrix)

Форма матрицы: (5, 5)
Размер матрицы: 25
Размерность матрицы 2


**2.3.1 Задание**

In [58]:
import pandas as pd
a = pd.Series([0,1], ['x','y'])
b = pd.Series([5,6], ['x','y'])

dX = a[0] - b[0]
dY = a[1] - b[1]
res = (dX ** 2 + dY ** 2) ** 0.5
print(res)

7.0710678118654755


**2.3.2 Задание**

In [65]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/donner_party.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

age  gender    status
0   23  female  survived
1   40    male      died
2   40  female      died
3   30  female  survived
4   28  female  survived

**2.3.3 Задание**

In [81]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/donner_party.csv'
dataframe = pd.read_csv(url)
dataframe.head(1)

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [76]:
dataframe.tail(3)


age  gender    status
42   23  female      died
43   24  female  survived
44   25    male      died

In [ ]:
dataframe.shape


In [ ]:
dataframe.describe()