In [1]:
# (1)
import numpy as np
from sklearn.datasets import load_digits, load_boston


def sigmoid(x):
    return 1 / (1 + np.exp(-x))


class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias

    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return sigmoid(total)


class OurNeuralNetwork:
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)

    def feedforward(self, inputs):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1


network = OurNeuralNetwork()
x = np.array([2, 3, 4])
print(network.feedforward(x))

0.8151036049051821


In [2]:
# (2)
import numpy as np


def tanh(x):
    return np.tanh(x)


class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias

    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return tanh(total)


class OurNeuralNetwork:
    def __init__(self):
        weights = np.array([1, 0])
        bias = 1
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
        self.o2 = Neuron(weights, bias)

    def feedforward(self, inputs):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2]))
        out_o2 = self.o2.feedforward(np.array([out_h1, out_h2]))
        return out_o1, out_o2


network = OurNeuralNetwork()
x = np.array([2, 3])
print(network.feedforward(x))

(0.9636765235959711, 0.9636765235959711)


In [3]:
# tanh
import numpy as np


def tanh(x):
    return np.tanh(x)


class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias

    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return tanh(total)


class OurNeuralNetwork:
    def __init__(self):
        weights = np.array([1, 0])
        bias = 1
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
        self.o2 = Neuron(weights, bias)

    def feedforward(self, inputs):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2]))
        out_o2 = self.o2.feedforward(np.array([out_h1, out_h2]))
        return out_o1, out_o2


network = OurNeuralNetwork()
x = np.array([2, 3])
print(network.feedforward(x))

(0.9636765235959711, 0.9636765235959711)


In [4]:
# sigmoid
import numpy as np


def sigmoid(x):
    return 1 / (1 + np.exp(-x))


class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias

    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return sigmoid(total)


class OurNeuralNetwork:
    def __init__(self):
        weights = np.array([1, 0])
        bias = 1
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
        self.o2 = Neuron(weights, bias)

    def feedforward(self, inputs):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2]))
        out_o2 = self.o2.feedforward(np.array([out_h1, out_h2]))
        return out_o1, out_o2


network = OurNeuralNetwork()
x = np.array([2, 3])
print(network.feedforward(x))

(0.8757270529783324, 0.8757270529783324)


In [7]:
# relu
import numpy as np

def relu(x):
    return max(0, x)

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias

    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return relu(total)
    
class OurNeuralNetwork:
    def __init__(self):
        weights = np.array([1, 0])
        bias = 1
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
        self.o2 = Neuron(weights, bias)

    def feedforward(self, inputs):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2]))
        out_o2 = self.o2.feedforward(np.array([out_h1, out_h2]))
        return out_o1, out_o2


network = OurNeuralNetwork()
x = np.array([2, 3])
print(network.feedforward(x))

(4, 4)


In [11]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_digits, load_boston
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

digits = load_digits()
x_digits, y_digits = digits.data, digits.target
print('Dataset Sizes : ', x_digits.shape, y_digits.shape)

boston = load_boston()
x_boston, y_boston = boston.data, boston.target
print('Dataset Sizes : ', x_boston.shape, y_boston.shape)

urls = {
    'class': r'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv',
    'reg': r'https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv'
}

print('**********MLPClassifier**********\n')
class_data = pd.read_csv(urls['class'])
x_data, y_data = class_data['sepal.length'], class_data['sepal.width']
print('Dataset Sizes : ', x_data.shape, y_data.shape)

x_train, x_test, y_train, y_test = train_test_split(x_digits, y_digits, train_size=.80, test_size=.20, stratify=y_digits, random_state=123)
print('Train/Test Sizes : ', x_train.shape, x_test.shape, y_train.shape, y_test.shape)

from sklearn.neural_network import MLPClassifier

mlp_classifier = MLPClassifier(random_state=123)
mlp_classifier.fit(x_train, y_train)

y_preds = mlp_classifier.predict(x_test)

print(y_preds[:15])
print(y_test[:15])
# Метод Score для оценки точности моделей классификации
print('Test Accuracy : %.3f'%mlp_classifier.score(x_test, y_test))

print('Training Accuracy : %.3f'%mlp_classifier.score(x_train, y_train))

print('Loss : ', mlp_classifier.loss_)
print('Number of Coefs : ', len(mlp_classifier.coefs_))
print('Number of Intercepts : ', len(mlp_classifier.intercepts_))
print('Number of Iterations for Which Estimator Ran : ', mlp_classifier.n_iter_)
print('Name of Output Layer Activation Function : ', mlp_classifier.out_activation_)




print('\n**********MLPRegressor**********\n')

reg_data = pd.read_csv(urls['reg'])
x_data, y_data = reg_data['YearsExperience'], reg_data['Salary']
print('Dataset Sizes : ', x_data.shape, y_data.shape)

x_train, x_test, y_train, y_test = train_test_split(x_boston, y_boston, train_size=.80, test_size=.20, random_state=123)
print('Train/Test Sizes : ', x_train.shape, x_test.shape, y_train.shape, y_test.shape)

from sklearn.neural_network import MLPRegressor

mlp_regressor = MLPRegressor(random_state=123)
mlp_regressor.fit(x_train, y_train)

y_preds = mlp_regressor.predict(x_test)

print(y_preds[:10])
print(y_test[:10])
# Метод Score оценивает точность моделей классификации
print('Test R^2 Score : %.3f'%mlp_regressor.score(x_test, y_test))
print('Training R^2 Score : %.3f'%mlp_regressor.score(x_train, y_train))

print('Loss : ', mlp_regressor.loss_)
print('Number of Coefs : ', len(mlp_regressor.coefs_))
[weights.shape for weights in mlp_regressor.coefs_]
print('Number of Iterations for Which Estimator Ran : ', mlp_regressor.n_iter_)
print('Name of Output Layer Activation Function : ', mlp_regressor.out_activation_)

Dataset Sizes :  (1797, 64) (1797,)
Dataset Sizes :  (506, 13) (506,)
**********MLPClassifier**********

Dataset Sizes :  (150,) (150,)
Train/Test Sizes :  (1437, 64) (360, 64) (1437,) (360,)


c:\Users\sasha\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

[5 9 9 6 1 6 6 9 8 7 4 2 1 4 3]
[5 9 9 6 1 6 6 9 8 7 4 2 1 4 3]
Test Accuracy : 0.983
Training Accuracy : 1.000
Loss :  0.0034728684994180608
Number of Coefs :  2
Number of Intercepts :  2
Number of Iterations for Which Estimator Ran :  125
Name of Output Layer Activation Function :  softmax

**********MLPRegressor**********

Dataset Sizes :  (30,) (30,)
Train/Test Sizes :  (404, 13) (102, 13) (404,) (102,)
[ 7.32543601 24.33417853 32.46700507 15.19086054 25.6749167  25.07797685
 27.20985668  2.62269853 15.25691994 28.02637784]
[15.  26.6 45.4 20.8 34.9 21.9 28.7  7.2 20.  32.2]
Test R^2 Score : 0.462
Training R^2 Score : 0.510
Loss :  28.538174061119626
Number of Coefs :  2
Number of Iterations for Which Estimator Ran :  130
Name of Output Layer Activation Function :  identity
